### ISSUE TITLE
Add support for models extra path

### ISSUE THREAD

**Issue by alexisrolland** [kijai/ComfyUI-Florence2#58]
Hi Kijai,
Thank you for creating this node.

ComfyUI allows to provide a custom path to store models in a single location and load them from there:
https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example

I have been using it successfully with other models, but it seems the Florence 2 nodes do not support this feature:

My `extra_model_paths.yaml` is as follow:
```yml
comfyui:
    base_path: D:\alexis\ComfyUI-Models\
    checkpoints: models\checkpoints\
    clip_vision: models\clip_vision\
    controlnet: models\controlnet\
    depthanything: models\depthanything\
    insightface: models\insightface\
    ipadapter: models\ipadapter\
    LLM: models\LLM\
    loras: models\loras\
    upscale_models: models\upscale_models\
``` 

ComfyUI-Florence2 returns the error:
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\alexis\\ComfyUI-Creative-Upscale\\ComfyUI\\models\\LLM'

It should search the models in the path ` D:\alexis\ComfyUI-Models\models\LLM\`

Cheers!
